-- V1__initial_schema.sql
--
-- Canonical initial schema for AutoTrader.
--
-- This migration represents the schema that Hibernate currently expects.
-- Existing production Neon will later be baselined at version 1 rather
-- than having this migration executed against its existing tables.

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(255) NOT NULL,
                       last_name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       phone_number VARCHAR(255),
                       role VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE vehicle_listings (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  title VARCHAR(255) NOT NULL,
                                  description TEXT,
                                  price NUMERIC(38, 2) NOT NULL,
                                  vehicle_year INTEGER NOT NULL,
                                  make VARCHAR(255),
                                  model VARCHAR(255),
                                  mileage INTEGER NOT NULL,
                                  fuel_type VARCHAR(255) NOT NULL,
                                  transmission VARCHAR(255) NOT NULL,
                                  body_type VARCHAR(255) NOT NULL,
                                  city VARCHAR(255),
                                  status VARCHAR(255) NOT NULL,
                                  seller_id BIGINT NOT NULL,
                                  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                                  CONSTRAINT fk_vehicle_listings_seller
                                      FOREIGN KEY (seller_id)
                                          REFERENCES users (id)
);

CREATE TABLE vehicle_images (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                listing_id BIGINT NOT NULL,
                                original_filename VARCHAR(255) NOT NULL,
                                storage_filename VARCHAR(255) NOT NULL,
                                content_type VARCHAR(255) NOT NULL,
                                file_size BIGINT NOT NULL,
                                display_order INTEGER,
                                is_primary BOOLEAN NOT NULL,
                                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                                CONSTRAINT uk_vehicle_images_storage_filename
                                    UNIQUE (storage_filename),

                                CONSTRAINT fk_vehicle_images_listing
                                    FOREIGN KEY (listing_id)
                                        REFERENCES vehicle_listings (id)
);

CREATE TABLE favorites (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id BIGINT NOT NULL,
                           listing_id BIGINT NOT NULL,
                           created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                           CONSTRAINT uk_favorite_user_listing
                               UNIQUE (user_id, listing_id),

                           CONSTRAINT fk_favorites_user
                               FOREIGN KEY (user_id)
                                   REFERENCES users (id),

                           CONSTRAINT fk_favorites_listing
                               FOREIGN KEY (listing_id)
                                   REFERENCES vehicle_listings (id)
);

CREATE TABLE conversations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               buyer_id BIGINT NOT NULL,
                               seller_id BIGINT NOT NULL,
                               listing_id BIGINT NOT NULL,
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                               CONSTRAINT uk_conversation_buyer_seller_listing
                                   UNIQUE (buyer_id, seller_id, listing_id),

                               CONSTRAINT fk_conversations_buyer
                                   FOREIGN KEY (buyer_id)
                                       REFERENCES users (id),

                               CONSTRAINT fk_conversations_seller
                                   FOREIGN KEY (seller_id)
                                       REFERENCES users (id),

                               CONSTRAINT fk_conversations_listing
                                   FOREIGN KEY (listing_id)
                                       REFERENCES vehicle_listings (id)
);

CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          conversation_id BIGINT NOT NULL,
                          sender_id BIGINT NOT NULL,
                          content TEXT NOT NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                          CONSTRAINT fk_messages_conversation
                              FOREIGN KEY (conversation_id)
                                  REFERENCES conversations (id),

                          CONSTRAINT fk_messages_sender
                              FOREIGN KEY (sender_id)
                                  REFERENCES users (id)
);

CREATE INDEX idx_conversation_buyer
    ON conversations (buyer_id);

CREATE INDEX idx_conversation_seller
    ON conversations (seller_id);

CREATE INDEX idx_conversation_listing
    ON conversations (listing_id);

CREATE INDEX idx_message_conversation_created_at
    ON messages (conversation_id, created_at);

CREATE INDEX idx_message_sender
    ON messages (sender_id);